- name: Install qemu-guest-agent on Ubuntu
  hosts: Ubuntu
  become: true
  tasks:
    - name: Install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: true

- name: Install qemu-guest-agent on Debian
  hosts: Debian
  become: true
  tasks:
    - name: Install qemu-guest-agent
      apt:
        name: qemu-guest-agent
        state: present
        update_cache: true

- name: Install qemu-guest-agent on RHEL
  hosts: RHEL
  become: true
  tasks:
    - name: Install qemu-guest-agent
      yum:
        name: qemu-guest-agent
        state: present
        update_cache: true
